title: "Hi, I'm Ella Beiser!"
logo: /Assets/headshot 2.png
description: Bilingual journalist living in Santiago, Chile.

Thus far, the bulk of my reporting has focused on immigration, higher education and local news.

I’m skilled in Spanish–English translation, data wrangling and map making.

I can be reached at my email, ellabeiser606@gmail.com.
show_downloads: false
theme: jekyll-theme-minimal
