title: "Hi, I'm Ella Beiser!"
logo: /Assets/headshot 2.png
description: Bilingual journalist living in Santiago, Chile. I can be reached at my email, ellabeiser606@gmail.com.
show_downloads: false
theme: jekyll-theme-minimal
